language: python
python: '3.6'
# Install the codecov pip dependency
install:
  - pip install codecov

# Run the unit test
script:
  - python Prueba.py
  - coverage run Prueba.py
  
# Push the results back to codecov
after_success:
  - codecov
