language: python
python: '3.6'
# Install the codecov pip dependency
install:
  - pip install codecov
  - pip install python-coveralls
#Configurando SonnarCloud
addons:
  sonarcloud:
    organization: "ylvaldes-github"
    token:
        secure: "8f22f0333e756f7379bcb44718527f65f19ea57f"

# Run the unit test
script:
  - python Prueba.py
  - coverage run Prueba.py
  - sonar-scanner
  
# Push the results back to codecov
after_success:
  - codecov
  - coveralls
  
notifications:
  slack: developerteamgrupo:IykMDkddgWiZEjsshJAiJeYx